name: personal_chat
description: My own private chat with video, voice and stickers

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  bloc: ^0.11.0
  flutter_bloc: ^0.9.0
  firebase_auth: ^0.8.2
  firebase_storage: ^2.1.0+1
  shared_preferences: ^0.5.1+2
  cloud_firestore: ^0.9.7
  connectivity: ^0.4.2
  flutter_advanced_networkimage: ^0.4.15
  equatable: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true